/* Generated By:JavaCC: Do not edit this line. CMaisMenosTreeConstants.java Version 7.0.12 */
package compilador;

public interface CMaisMenosTreeConstants
{
  public int JJTMAIN = 0;
  public int JJTCOMANDOS = 1;
  public int JJTDECLARAVARIAVEL = 2;
  public int JJTDECLARAVARIAVELFOR = 3;
  public int JJTTIPOVARIAVEL = 4;
  public int JJTOPERADORMATEMATICO = 5;
  public int JJTOPERADORLOGICO = 6;
  public int JJTEXPRESSAO = 7;
  public int JJTEXPRESSAOLOGICA = 8;
  public int JJTTERMO = 9;
  public int JJTATRIBUIVALOR = 10;
  public int JJTIF = 11;
  public int JJTWHILE = 12;
  public int JJTFOR = 13;
  public int JJTINCREMENTOOUDECREMENTO = 14;
  public int JJTNASCOXAS = 15;
  public int JJTPONTOVIRGULA = 16;
  public int JJTVIRGULA = 17;
  public int JJTTIPOISSO = 18;
  public int JJTEUACHO = 19;
  public int JJTABREPAR = 20;
  public int JJTFECHAPAR = 21;
  public int JJTIGUAL = 22;
  public int JJTSEPA = 23;
  public int JJTACONTECE = 24;
  public int JJTVAINAFE = 25;
  public int JJTID = 26;
  public int JJTMENOS = 27;
  public int JJTPOUCACOISA = 28;
  public int JJTFALOUEDISSE = 29;
  public int JJTMAISOUMENOS = 30;
  public int JJTMAIS = 31;
  public int JJTMULTIPLICADO = 32;
  public int JJTDIVIDIDO = 33;
  public int JJTNUMERO = 34;
  public int JJTIGUALIGUAL = 35;
  public int JJTDIFERENTE = 36;
  public int JJTMENORIGUAL = 37;
  public int JJTMAIORIGUAL = 38;
  public int JJTMENOR = 39;
  public int JJTMAIOR = 40;
  public int JJTMAISIGUAL = 41;
  public int JJTMENOSIGUAL = 42;
  public int JJTMAISMAIS = 43;
  public int JJTMENOSMENOS = 44;


  public String[] jjtNodeName = {
    "main",
    "Comandos",
    "DeclaraVariavel",
    "DeclaraVariavelFor",
    "TipoVariavel",
    "OperadorMatematico",
    "OperadorLogico",
    "Expressao",
    "ExpressaoLogica",
    "Termo",
    "AtribuiValor",
    "If",
    "While",
    "For",
    "IncrementoOuDecremento",
    "NasCoxas",
    "PontoVirgula",
    "Virgula",
    "TipoIsso",
    "EuAcho",
    "AbrePar",
    "FechaPar",
    "Igual",
    "Sepa",
    "Acontece",
    "Vainafe",
    "Id",
    "Menos",
    "PoucaCoisa",
    "FaloueDisse",
    "MaisOuMenos",
    "Mais",
    "Multiplicado",
    "Dividido",
    "Numero",
    "IgualIgual",
    "Diferente",
    "MenorIgual",
    "MaiorIgual",
    "Menor",
    "Maior",
    "MaisIgual",
    "MenosIgual",
    "MaisMais",
    "MenosMenos",
  };
}
/* JavaCC - OriginalChecksum=bbbe0a816114e3d27765466aeff17a7a (do not edit this line) */
