/* Generated By:JJTree&JavaCC: Do not edit this line. CMaisMenosConstants.java */
package compilador;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface CMaisMenosConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int INICIOPROGRAMA = 5;
  /** RegularExpression Id. */
  int PONTOVIRGULA = 6;
  /** RegularExpression Id. */
  int VIRGULA = 7;
  /** RegularExpression Id. */
  int ABREBLOCO = 8;
  /** RegularExpression Id. */
  int FECHABLOCO = 9;
  /** RegularExpression Id. */
  int ABREPAR = 10;
  /** RegularExpression Id. */
  int FECHAPAR = 11;
  /** RegularExpression Id. */
  int TIPOINTEIRO = 12;
  /** RegularExpression Id. */
  int TIPOFLOAT = 13;
  /** RegularExpression Id. */
  int TIPOBOOL = 14;
  /** RegularExpression Id. */
  int SEPA = 15;
  /** RegularExpression Id. */
  int ACONTECE = 16;
  /** RegularExpression Id. */
  int VAINAFE = 17;
  /** RegularExpression Id. */
  int DECIMAL = 18;
  /** RegularExpression Id. */
  int DIGITO = 19;
  /** RegularExpression Id. */
  int ID = 20;
  /** RegularExpression Id. */
  int LETRA = 21;
  /** RegularExpression Id. */
  int IGUAL_LOG = 22;
  /** RegularExpression Id. */
  int DIFERENTE = 23;
  /** RegularExpression Id. */
  int MENOR_IGUAL = 24;
  /** RegularExpression Id. */
  int MAIOR_IGUAL = 25;
  /** RegularExpression Id. */
  int MENOR = 26;
  /** RegularExpression Id. */
  int MAIOR = 27;
  /** RegularExpression Id. */
  int INCREMENTO = 28;
  /** RegularExpression Id. */
  int DECREMENTO = 29;
  /** RegularExpression Id. */
  int MAIS_IGUAL = 30;
  /** RegularExpression Id. */
  int MENOS_IGUAL = 31;
  /** RegularExpression Id. */
  int MAIS = 32;
  /** RegularExpression Id. */
  int MENOS = 33;
  /** RegularExpression Id. */
  int MULTI = 34;
  /** RegularExpression Id. */
  int DIVISAO = 35;
  /** RegularExpression Id. */
  int IGUAL = 36;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\r\"",
    "\"\\t\"",
    "\"\\n\"",
    "\"nascoxas\"",
    "\";\"",
    "\",\"",
    "\"tipoisso\"",
    "\"euacho\"",
    "\"(\"",
    "\")\"",
    "\"poucacoisa\"",
    "\"falouedisse\"",
    "\"maisoumenos\"",
    "\"sepa\"",
    "\"acontece\"",
    "\"vainafe\"",
    "<DECIMAL>",
    "<DIGITO>",
    "<ID>",
    "<LETRA>",
    "<IGUAL_LOG>",
    "<DIFERENTE>",
    "<MENOR_IGUAL>",
    "<MAIOR_IGUAL>",
    "<MENOR>",
    "<MAIOR>",
    "<INCREMENTO>",
    "<DECREMENTO>",
    "<MAIS_IGUAL>",
    "<MENOS_IGUAL>",
    "<MAIS>",
    "<MENOS>",
    "<MULTI>",
    "<DIVISAO>",
    "<IGUAL>",
  };

}
